update builtin targets to Rust 1.54.0
EmbarkStudios/cfg-expr pull request #38
Opened 2021-08-30 22:52 UTC by sunshowers

### Checklist

* [x] I have read the [Contributor Guide](../../CONTRIBUTING.md)
* [x] I have read and agree to the [Code of Conduct](../../CODE_OF_CONDUCT.md)
* [x] I have added a description of my changes and why I'd like them included in the section below

### Description of Changes

This includes several changes:

1. Rust 1.54 introduces the new WASM target family. More target families
might be added in the future, so make this enum open-ended like Arch, Os
and others.
2. Use builtin constants for target-lexicon matching.
3. Update the builtin targets and target-lexicon, and handle the new bpf
architectures and wasm family.

2021-08-30 22:53 UTC, sunshowers commented
I believe that with this change a new version of cfg-expr can be released.

2021-08-31 06:26 UTC, Jake-Shadle requested changes
Nice, thanks for the PR! I'll do a release with this later today.

2021-08-31 06:26 UTC, Jake-Shadle commented on src/targets.rs
>  pub use builtins::ALL_BUILTINS;
```suggestion
/// A list of all of the [builtin](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_target/spec/index.html#modules)
/// targets known to rustc, as of 1.54.0
pub use builtins::ALL_BUILTINS;
```

2021-08-31 06:26 UTC, Jake-Shadle commented on src/targets.rs
> +#[non_exhaustive]
```suggestion
```

2021-08-31 06:27 UTC, Jake-Shadle approved these changes

2021-08-31 06:33 UTC, merged